"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 21:24:09.389426
"""

import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_enrichment',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('kev_listed', sa.Boolean(), nullable=False),
    sa.Column('kev_date_added', sa.Date(), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('has_public_exploit', sa.Boolean(), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('product', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_table('source_refresh',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('target_domain', sa.String(length=255), nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('discovered_by_scan_id', sa.String(length=36), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('technology', sa.String(length=255), nullable=True),
    sa.Column('discovered_by_tool', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovered_by_scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'hostname', 'port', 'protocol', name='uq_asset_identity')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_tenant', ['tenant_id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=320), nullable=False),
    sa.Column('source_tool', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_observations_kind', ['kind'], unique=False)
        batch_op.create_index('ix_observations_scan', ['scan_id'], unique=False)

    op.create_table('asset_criticality',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('tagged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detection_method', sa.String(length=32), nullable=False),
    sa.Column('detected_by_tool', sa.String(length=64), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['cve_id'], ['cve_enrichment.cve_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'cve_id', name='uq_finding_identity')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_findings_asset', ['asset_id'], unique=False)
        batch_op.create_index('ix_findings_cve', ['cve_id'], unique=False)
        batch_op.create_index('ix_findings_risk', ['risk_score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('ix_findings_risk')
        batch_op.drop_index('ix_findings_cve')
        batch_op.drop_index('ix_findings_asset')

    op.drop_table('findings')
    op.drop_table('asset_criticality')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index('ix_observations_scan')
        batch_op.drop_index('ix_observations_kind')

    op.drop_table('observations')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_tenant')

    op.drop_table('assets')
    op.drop_table('scans')
    op.drop_table('tenants')
    op.drop_table('source_refresh')
    op.drop_table('cve_enrichment')
    # ### end Alembic commands ###
