"""scan warnings and criticality source

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-18 23:47:45.690018
"""

import sqlalchemy as sa
from alembic import op

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_criticality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=16), server_default='heuristic', nullable=False))

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warnings', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('warnings')

    with op.batch_alter_table('asset_criticality', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
